select * from commodity_price_info I
join STATE_INFO S on S.STATE_ID = I.STATE_ID

select * from STATE_INFO


-- Root query.
-- This just gets the price data 
-- saved from craigslist
select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO


-- This is all of the regions
-- Region_1_Northeast
-- Region_2_Midwest
-- Region_3_South
-- Region_4_West
select distinct REGION_SK_FED from STATE_INFO;

-- Get list of state id's by region
select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_1_Northeast';
select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_2_Midwest';
select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_3_South';
select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_4_West';


-- Put pieces together to get COMMODITY_PRICE_INFO by region
select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ( select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_1_Northeast');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ( select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_2_Midwest');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ( select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_3_South');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ( select STATE_ID from STATE_INFO where REGION_SK_FED = 'Region_4_West');


-- Most granular, get by state.  
-- For code version, we only need the sql in a method that gets the state id, and returns the query.
select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('AK');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('AL');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('AR');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('AZ');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('CA');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('CO');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('CT');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('DC');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('DE');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('FL');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('GA');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('HI');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('IA');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('ID');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('IL');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('IN');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('KS');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('KY');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('LA');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('MA');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('MD');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('ME');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('MI');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('MN');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('MO');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('MS');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('MT');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('NC');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('ND');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('NE');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('NH');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('NJ');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('NM');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('NV');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('NY');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('OH');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('OK');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('OR');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('PA');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('RI');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('SC');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('SD');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('TN');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('TX');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('UT');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('VA');

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('VT');
and SCAN_DATE = '2020-08-09 00:00:00.000';

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('WA');
and SCAN_DATE = '2020-08-09 00:00:00.000';

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('WI');
and SCAN_DATE = '2020-08-09 00:00:00.000';

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('WV');
and SCAN_DATE = '2020-08-09 00:00:00.000';

select STATE_ID, AD_SOURCE_INFO_ID_NAME, COMMODITY, ASKING_PRICE, TITLE, NEIGHBORHOOD, SCAN_DATE
from COMMODITY_PRICE_INFO
where STATE_ID IN ('WY')
and SCAN_DATE = '2020-08-09 00:00:00.000';







